### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'far_points_first'

### ISSUE THREAD

**Issue by Amitnuk** [Vegeta2020/CIA-SSD#16]
Dear Sir 

I found an error when trying to test the CIA-SSD with kitti_all_vfev3_spmiddlefhd_rpn1_mghead_syncbn.py, I am not quite able to solve it. Any suggestion on how, I would really appreciate.

**Comment by Vegeta2020** [comment]
You may remove the code lines containining "far_point_first" in the called preprocess file.

**Comment by Amitnuk** [comment]
To be more precise this is the error I am getting :

Namespace(checkpoint='latest.pth', config='../examples/second/configs/kitti_all_vfev3_spmiddlefhd_rpn1_mghead_syncbn.py', eval=['bbox'], json_out='json_out.json', launcher='none', local_rank=0, out='out.pkl', show=True, tmpdir=None, txt_result='True')
Traceback (most recent call last):
  File "test.py", line 180, in <module>
    main()
  File "test.py", line 135, in main
    dataset = build_dataset(cfg.data.val)
  File "/data/SAVIM/kuntima/3DbenchmarkGIT/CIA-SSD/det3d/datasets/builder.py", line 41, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/data/SAVIM/kuntima/3DbenchmarkGIT/CIA-SSD/det3d/utils/registry.py", line 76, in build_from_cfg
    return obj_cls(**args)
  File "/data/SAVIM/kuntima/3DbenchmarkGIT/CIA-SSD/det3d/datasets/kitti/kitti.py", line 23, in __init__
    super(KittiDataset, self).__init__(root_path, info_path, pipeline, test_mode=test_mode)
  File "/data/SAVIM/kuntima/3DbenchmarkGIT/CIA-SSD/det3d/datasets/custom.py", line 44, in __init__
    self.pipeline = Compose(pipeline)
  File "/data/SAVIM/kuntima/3DbenchmarkGIT/CIA-SSD/det3d/datasets/pipelines/compose.py", line 14, in __init__
    transform = build_from_cfg(transform, PIPELINES)
  File "/data/SAVIM/kuntima/3DbenchmarkGIT/CIA-SSD/det3d/utils/registry.py", line 76, in build_from_cfg
    return obj_cls(**args)
  File "/data/SAVIM/kuntima/3DbenchmarkGIT/CIA-SSD/det3d/datasets/pipelines/preprocess_v4.py", line 224, in __init__
    self.far_points_first = cfg.far_points_first
  File "/data/SAVIM/kuntima/3DbenchmarkGIT/CIA-SSD/det3d/torchie/utils/config.py", line 29, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'far_points_first'

Since, far_points_first it's a boolean variable, I've forced it to be False and True, and in both instance I've got the following :  

Namespace(checkpoint='latest.pth', config='../examples/second/configs/kitti_all_vfev3_spmiddlefhd_rpn1_mghead_syncbn.py', eval=['bbox'], json_out='json_out.json', launcher='none', local_rank=0, out='out.pkl', show=True, tmpdir=None, txt_result='True')
Traceback (most recent call last):
  File "test.py", line 180, in <module>
    main()
  File "test.py", line 141, in main
    model = build_detector(cfg.model, train_cfg=None, test_cfg=cfg.test_cfg)
  File "/data/SAVIM/kuntima/3DbenchmarkGIT/CIA-SSD/det3d/models/builder.py", line 53, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/data/SAVIM/kuntima/3DbenchmarkGIT/CIA-SSD/det3d/models/builder.py", line 21, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/data/SAVIM/kuntima/3DbenchmarkGIT/CIA-SSD/det3d/utils/registry.py", line 76, in build_from_cfg
    return obj_cls(**args)
  File "/data/SAVIM/kuntima/3DbenchmarkGIT/CIA-SSD/det3d/models/detectors/voxelnet.py", line 9, in __init__
    super(VoxelNet, self).__init__(reader, backbone, neck, bbox_head, train_cfg, test_cfg, pretrained)
  File "/data/SAVIM/kuntima/3DbenchmarkGIT/CIA-SSD/det3d/models/detectors/single_stage.py", line 15, in __init__
    self.neck = builder.build_neck(neck)
  File "/data/SAVIM/kuntima/3DbenchmarkGIT/CIA-SSD/det3d/models/builder.py", line 33, in build_neck
    return build(cfg, NECKS)
  File "/data/SAVIM/kuntima/3DbenchmarkGIT/CIA-SSD/det3d/models/builder.py", line 21, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/data/SAVIM/kuntima/3DbenchmarkGIT/CIA-SSD/det3d/utils/registry.py", line 64, in build_from_cfg
    "{} is not in the {} registry".format(obj_type, registry.name)
KeyError: 'RPN is not in the neck registry'

But this does not happen when I am just testing car, it works as it should.
