### ISSUE TITLE
A problem about training data sets.

### ISSUE THREAD

**Issue by phdmuzi** [Vegeta2020/CIA-SSD#23]
When I use command 'python train.py' to train a model based on KITTI.
An error occurred:
Traceback (most recent call last):
  File "train.py", line 116, in <module>
    main()
  File "train.py", line 113, in main
    train_detector(model, datasets, cfg, distributed=distributed, validate=args.validate, logger=logger,)
  File "/home/lixusheng/CIA-SSD/CIA-SSD/det3d/torchie/apis/train.py", line 322, in train_detector
    trainer.run(data_loaders, cfg.workflow, cfg.total_epochs, local_rank=cfg.local_rank)
  File "/home/lixusheng/CIA-SSD/CIA-SSD/det3d/torchie/trainer/trainer.py", line 394, in run
    epoch_runner(data_loaders[i], self.epoch, **kwargs)
  File "/home/lixusheng/CIA-SSD/CIA-SSD/det3d/torchie/trainer/trainer.py", line 264, in train
    for i, data_batch in enumerate(data_loader):
  File "/home/lixusheng/anaconda3/envs/CIA-SSD/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/lixusheng/anaconda3/envs/CIA-SSD/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/lixusheng/anaconda3/envs/CIA-SSD/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/lixusheng/anaconda3/envs/CIA-SSD/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/lixusheng/anaconda3/envs/CIA-SSD/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/lixusheng/anaconda3/envs/CIA-SSD/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lixusheng/anaconda3/envs/CIA-SSD/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lixusheng/CIA-SSD/CIA-SSD/det3d/datasets/kitti/kitti.py", line 163, in __getitem__
    return self.get_sensor_data(idx, with_gp=True)
  File "/home/lixusheng/CIA-SSD/CIA-SSD/det3d/datasets/kitti/kitti.py", line 176, in get_sensor_data
    gp = self.get_road_plane(idx)
  File "/home/lixusheng/CIA-SSD/CIA-SSD/det3d/datasets/kitti/kitti.py", line 43, in get_road_plane
    with open(plane_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/KITTI_DATASET_ROOT/training/planes/003354.txt'
What puzzles me is that there is no such folder ‘/training/planes/’in Kitti dataset.

**Comment by www04576** [comment]
i have the same problem. have you solved it? thank you.

**Comment by www04576** [comment]
you can download the plane folder [here](https://blog.csdn.net/djboy1021/article/details/110883000)

**Comment by sjg918** [comment]
https://github.com/sshaoshuai/PointRCNN
https://drive.google.com/file/d/1d5mq0RXRnvHPVeKx6Q612z0YRO1t2wAp/view
