### ISSUE TITLE
When I run 'python ./tools/train.py', I encounter the following problems. How should I solve it

### ISSUE THREAD

**Issue by libingDY** [Vegeta2020/CIA-SSD#29]
Traceback (most recent call last):
  File "./tools/train.py", line 116, in <module>
    main()
  File "./tools/train.py", line 113, in main
    train_detector(model, datasets, cfg, distributed=distributed, validate=args.validate, logger=logger,)
  File "/home/libing/newstorage/3Dobjectdetector/CIA-SSD-master/det3d/torchie/apis/train.py", line 322, in train_detector
    trainer.run(data_loaders, cfg.workflow, cfg.total_epochs, local_rank=cfg.local_rank)
  File "/home/libing/newstorage/3Dobjectdetector/CIA-SSD-master/det3d/torchie/trainer/trainer.py", line 394, in run
    epoch_runner(data_loaders[i], self.epoch, **kwargs)
  File "/home/libing/newstorage/3Dobjectdetector/CIA-SSD-master/det3d/torchie/trainer/trainer.py", line 272, in train
    outputs = self.batch_processor_inline(self.model, data_batch, train_mode=True, **kwargs)
  File "/home/libing/newstorage/3Dobjectdetector/CIA-SSD-master/det3d/torchie/trainer/trainer.py", line 243, in batch_processor_inline
    losses = model(example, return_loss=True)
  File "/home/libing/anaconda3/envs/HVPR/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/libing/newstorage/3Dobjectdetector/CIA-SSD-master/det3d/models/detectors/voxelnet.py", line 38, in forward
    return self.bbox_head.loss(example, preds)
  File "/home/libing/newstorage/3Dobjectdetector/CIA-SSD-master/det3d/models/bbox_heads/mg_head_v4_release.py", line 605, in loss
    iou_pos_preds = iou_preds.view(batch_size, -1, 1)[pos_pred_mask]
IndexError: The shape of the mask [4, 70400] at index 1 does not match the shape of the indexed tensor [4, 71912, 1] at index 1

**Comment by DeclK** [comment]
I met the same question. I think it's a small bug...
It's because this repo recent has a new [commit](https://github.com/Vegeta2020/CIA-SSD/commit/fac6e0bfabef2c47593a598b9e6cfa886106fb65), which changed the kernel size of conv_iou. Just change it back will solve this issue

**Comment by Vegeta2020** [comment]
@DeclK @libingDY Thanks for your report, and I have changed it back. Note that kernal size as 1 or 3 has little impact on the performance.
